In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
RAW_FILE = "/kaggle/input/datasets/ahmedmohamed518/industrial-training-kit/Dataset for Data Analytics.xlsx"
df_raw = pd.read_excel(RAW_FILE)
 
# Keep a pristine copy of the original for comparison at the end
df = df_raw.copy()

In [3]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [5]:
df.shape

(1200, 14)

In [6]:
print(df.dtypes)

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [7]:
print(df.describe(include="all"))

          OrderID                 Date CustomerID  Product     Quantity  \
count        1200                 1200       1200     1200  1200.000000
unique       1200                  NaN       1189        7          NaN
top     ORD201183                  NaN     C46651  Printer          NaN
freq            1                  NaN          2      181          NaN
mean          NaN  2024-03-22 16:58:48        NaN      NaN     2.945833
min           NaN  2023-01-01 00:00:00        NaN      NaN     1.000000
25%           NaN  2023-08-03 18:00:00        NaN      NaN     2.000000
50%           NaN  2024-03-23 00:00:00        NaN      NaN     3.000000
75%           NaN  2024-11-08 12:00:00        NaN      NaN     4.000000
max           NaN  2025-06-30 00:00:00        NaN      NaN     5.000000
std           NaN                  NaN        NaN      NaN     1.407557

          UnitPrice ShippingAddress PaymentMethod OrderStatus TrackingNumber  \
count   1200.000000            1200          1200        1200           1200
unique          NaN             655             5           5           1200
top             NaN     533 Main St        Online   Cancelled    TRK83653396
freq            NaN               8           258         250              1
mean     356.412750             NaN           NaN         NaN            NaN
min       11.390000             NaN           NaN         NaN            NaN
25%      186.062500             NaN           NaN         NaN            NaN
50%      364.210000             NaN           NaN         NaN            NaN
75%      521.570000             NaN           NaN         NaN            NaN
max      699.930000             NaN           NaN         NaN            NaN
std      197.177146             NaN           NaN         NaN            NaN

        ItemsInCart CouponCode ReferralSource   TotalPrice
count   1200.000000        891           1200  1200.000000
unique          NaN          3              5          NaN
top             NaN   FREESHIP      Instagram          NaN
freq            NaN        313            259          NaN
mean       5.485000        NaN            NaN  1053.968300
min        1.000000        NaN            NaN    11.390000
25%        4.000000        NaN            NaN   410.520000
50%        5.000000        NaN            NaN   823.615000
75%        7.000000        NaN            NaN  1578.475000
max       10.000000        NaN            NaN  3456.400000
std        2.281983        NaN            NaN   819.856558

In [8]:
missing = df.isnull().sum()
print (missing)

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
total_dupes = df.duplicated().sum()
print(total_dupes)

id_dupes = df.duplicated(["OrderID"]).sum()
print(id_dupes)

0
0

In [11]:
df.nunique()

OrderID            1200
Date                671
CustomerID         1189
Product               7
Quantity              5
UnitPrice          1193
ShippingAddress     655
PaymentMethod         5
OrderStatus           5
TrackingNumber     1200
ItemsInCart          10
CouponCode            3
ReferralSource        5
TotalPrice         1195
dtype: int64

In [12]:
#Unique values in key categorical 
for col in ["OrderStatus", "PaymentMethod", "Product", "ReferralSource", "CouponCode"]:
    print(f"{col}: {df[col].unique()}")

OrderStatus: ['Shipped' 'Cancelled' 'Returned' 'Delivered' 'Pending']
PaymentMethod: ['Debit Card' 'Online' 'Credit Card' 'Gift Card' 'Cash']
Product: ['Monitor' 'Phone' 'Tablet' 'Chair' 'Printer' 'Laptop' 'Desk']
ReferralSource: ['Instagram' 'Referral' 'Email' 'Facebook' 'Google']
CouponCode: ['SAVE10' 'FREESHIP' nan 'WINTER15']

# --------------------

In [13]:
#Handling missing values in CouponCode 
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [14]:
#Remove Duplicates
df = df.drop_duplicates()
df.duplicated

<bound method DataFrame.duplicated of         OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1196  ORD201196 2024-03-04     C20095  Monitor         2     662.53
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1196     778 Main St        Online   Cancelled    TRK69207593            5
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1195   FREESHIP         Google      107.04
1196  No Coupon       Facebook     1325.06
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[1200 rows x 14 columns]>

In [15]:
#if we catch same Order ID but differ in other fields keep the First
df = df.drop_duplicates(subset=["OrderID"], keep="first")

# correct Data format (Date , numbers , text)

In [16]:
#format all Date column 
df["Date"] = pd.to_datetime(df["Date"]).dt.strftime("%Y-%m-%d")
 
print(f"{df['Date'].head(10)}")

0    2023-01-04
1    2024-08-23
2    2024-02-27
3    2023-10-15
4    2025-05-08
5    2023-10-23
6    2025-06-17
7    2023-05-12
8    2025-04-02
9    2023-11-21
Name: Date, dtype: object

In [17]:
#format all price columns 
for col in ["UnitPrice", "TotalPrice"]:
        df[col] = df[col].round(2)

In [18]:
  print(f"{df['UnitPrice'].head()}")
  print(f"{df['TotalPrice'].head()}")

0    570.62
1    151.35
2    550.68
3    273.19
4    626.01
Name: UnitPrice, dtype: float64
0    2853.10
1     302.70
2    2753.40
3     273.19
4    2504.04
Name: TotalPrice, dtype: float64

In [19]:
#format all Text
text_cols = ["Product", "OrderStatus", "PaymentMethod", "ReferralSource","ShippingAddress", "CouponCode"]

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

# Check Duplicates

In [20]:
# Check Duplicate OrderIDs
final_id_dupes = df.duplicated(subset=["OrderID"]).sum()
id_check = "PASS" if final_id_dupes == 0 else "FAIL"
print(f"Duplicate OrderIDs  : {final_id_dupes}  → {id_check}")

Duplicate OrderIDs  : 0  → PASS

In [21]:
# Check  Incorrectly formatted dates
import re
final_bad_dates = df["Date"].apply(lambda x: not bool(re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(x)))).sum()
date_check = "PASS" if final_bad_dates == 0 else "FAIL"
print(f"Bad date formats  : {final_bad_dates}  → {date_check}")

Bad date formats  : 0  → PASS